# Generated by Django 3.0.6 on 2020-05-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200529_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a test description for artsyy products'),
            preserve_default=False,
        ),
    ]
