# Generated by Django 3.0.6 on 2020-05-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200529_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('C', 'Cityscape'), ('L', 'Landscape'), ('W', 'Wildlife')], max_length=2),
        ),
    ]
